### ISSUE TITLE
No Selenium examples at all

### ISSUE THREAD

**Issue by stealthrabbi** [tsundberg/selenium-test-automation#1]
This project seems to be missing a lot. There are no selenium tests at all. The only source code here is some kind of example JUnit test that doesn't do anything.

**Comment by tsundberg** [comment]
This project does not miss anything. You miss context.

Attend one of my Selenium courses and you will understand.

**Comment by stealthrabbi** [comment]
OK, that response isn't helpful at all.

Apparently the actual code to look at is on a different branch than master. You should either merge that code to master, or specify that on the readme.

The master branch has a single java class on there and has nothing to do with selenium.

**Comment by tsundberg** [comment]
This is a starting point for the participants in a Selenium course I have. If you are interested, feel free to join next time I run it.

If you are looking for a Selenium tutorials, feel free to take a look at the different [blog posts](http://www.thinkcode.se/blog/category/Selenium) I have written about Selenium.
